#!/bin/sh /etc/rc.common
#
# Copyright (C) 2023 sirpdboy herboy2008@gmail.com
#

START=99
USE_PROCD=1

NAME=eqosplus
LOCK="/var/lock/$NAME.lock"

disable_offload() {
	if [ $(uci -q show firewall.@defaults[0] | grep -c flow_offloading) -ge 1 ]; then
		echo flow_offloading > /etc/.eqosplus_offload
		uci -q del firewall.@defaults[0].flow_offloading
		uci commit firewall
		/etc/init.d/firewall reload >/dev/null 2>&1
	elif [ $(uci -q show firewall.@defaults[0] | grep -c shortcut_fe) -ge 1 ]; then
		uci -q get firewall.@defaults[0].shortcut_fe_module > /etc/.eqosplus_offload
		uci -q del firewall.@defaults[0].shortcut_fe
		uci -q del firewall.@defaults[0].shortcut_fe_module
		uci commit firewall
		/etc/init.d/firewall reload >/dev/null 2>&1
		/etc/init.d/shortcut-fe restart
	fi
}

enable_offload() {
	offload_mode=$(cat /etc/.eqosplus_offload)
	rm -f /etc/.eqosplus_offload
	if [ "$offload_mode" = "flow_offloading" ]; then
		uci set firewall.@defaults[0].flow_offloading='1'
		uci commit firewall
		/etc/init.d/firewall reload >/dev/null 2>&1
	else
		uci set firewall.@defaults[0].shortcut_fe='1'
		uci set firewall.@defaults[0].shortcut_fe_module="$offload_mode"
		uci commit firewall
		/etc/init.d/firewall reload >/dev/null 2>&1
		/etc/init.d/shortcut-fe restart
	fi
}

start_instance() {
	 procd_open_instance
	 procd_set_param command /usr/bin/eqosplusctrl
	 procd_set_param respawn
	 procd_set_param stderr 1
	 procd_close_instance
}

_eqosplus_start() {
	 if [ "$(grep -c 'option enable .1.' /etc/config/$NAME 2>/dev/null)" -gt "0" ]; then
            disable_offload
	    touch $LOCK
	    eqosplus start
	    start_instance
	 fi
}

start_service(){
	[ -f $LOCK ] && exit
	stop_service
	_eqosplus_start
	rm -f $LOCK
}

service_triggers() {
 	 procd_add_reload_trigger 'eqosplus'
}

stop_service(){
	kill -9 $(busybox ps -w | grep 'eqosplusctrl' | grep -v 'grep' | awk '{print $1}') >/dev/null 2>&1
	rm -f $LOCK 2>/dev/null
	eqosplus stop
        [ -f "/etc/.eqosplus_offload" ] && enable_offload
}
